

# Useful Links

The following links lead to external trainings, tutorials, projects, documents, and papers related to topics covered by Working Packages of AIML4OS project 

### Earth Observation 


- <a href="https://eo-college.org/courses/" target="_blank">Introduction to Machine Learning for Earth Observation</a>
- <a href="https://www.oecd.org/en/about/programmes/the-oecd-laboratory-for-geospatial-analysis.html" target="_blank">The OECD Laboratory for Geospatial Analysis</a>
- <a href="https://cros.ec.europa.eu/group/earth-observation-statistics-eo4s/book-page/esas-newcomers-earth-observation-guide" target="_blank">ESA's Newcomers Earth Observation Guide | Eurostat CROS</a>
- <a href="https://dataspace.copernicus.eu/" target="_blank">Copernicus Data Space Ecosystem | Europe's eyes on Earth</a>
- <a href="https://euspa.wedeho.tech/" target="_blank">EUSPA - European Union Agency for the Space Programme (requires login)</a>
- <a href="https://www.copernicus.eu/en/opportunities/education/copernicus-mooc" target="_blank">Copernicus MOOC – Learn to harness the power of space data</a>
- <a href="http://www.eo4geo.eu/Languages/english/?BoKknowledgearea=basics-of-optical-remote-sensing" target="_blank">Basics of Optical Remote Sensing – EO4GEO</a>
- <a href="http://www.eo4geo.eu/BoKknowledgearea/image-processing-and-analysis/" target="_blank">Image processing and analysis – EO4GEO</a>
- <a href="https://www.fao.org/statistics/events/detail-events/en/c/1631683/" target="_blank">FAO Webinar Series: Earth observation data for agricultural statistics</a>
- <a href="https://eo4society.esa.int/training-education/" target="_blank">ESA - EO science for society</a>
- <a href="https://eo4society.esa.int/resources/12th-esa-training-eo-2022/" target="_blank">12th ESA Training Course on Earth Observation 2022</a>
- <a href="https://space4climate.com/" target="_blank"> Space4Climate (UK Agency) </a> activities enable a seamless supply chain of climate data from space assets; helping to identify end user requirements and facilitate trusted climate services development to meet these, promoting global economic and societal benefit.


#### EO resources without links

- 2021_ EO_Use of satellite data - file missions, file indices 1 and 2
- From strategies to practical use of Earth observation data for official statistics (2023)
- Statistical Cartography (2024)
- Integration of statistics and geospatial information – From geocoding to statistical maps  (2024)
- Advanced Earth observation (2024)
- Usage of the Copernicus data space ecosystem for earth observation data for official statistics (2025)
- Educational materials from the 12th ESA Training Course on Earth Observation 2022 held in Riga, Latvia, from 27 June – 01 July 2022.


---

### Programming

- <a href="https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/" target="_blank">Insee - Best programming practices with Git and R</a>
- <a href="https://pythonds.linogaliana.fr/en/" target="_blank">Lino Galiana from Insee - Data science with Python</a>
- <a href="https://inseefrlab.github.io/formation-mlops/slides/en/index.html" target="_blank">Insee - Introduction to MLOps with MLflow (slides)</a>
- <a href="https://ensae-reproductibilite.github.io/website/" target="_blank">Insee - Putting data science projects into production</a>
- <a href="https://inseefrlab.github.io/DT_methodes_ensemblistes/" target="_blank">Insee - Introduction to ensemble algorithms</a>
- <a href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">Python Data Science Handbook</a>
- <a href="https://r4ds.had.co.nz/index.html" target="_blank">R for Data Science</a>
- <a href="https://www.holehouse.org/mlclass/" target="_blank">Standford Machine Learning Notes</a>
- <a href="https://trevorhastie.github.io/ISLR/" target="_blank">An Introduction to Statistical Learning with Applications in R</a>
- <a href="https://unece.org/sites/default/files/2022-09/ECECESSTAT20216.pdf" target="_blank">UNECE - Machine Learning for Official Statistics</a>
- <a href="https://pure.tue.nl/ws/portalfiles/portal/192519868/Survey_Statistician_2021_July_N84_02.pdf" target="_blank">Puts, Daas - Machine Learning from the Perspective of Official Statistic</a>
- <a href="https://statswiki.unece.org/download/attachments/285216420/QF4SA_2020_Final.pdf" target="_blank">UNECE - A quality framework for statistical algorithms</a>
- <a href="https://www.sciencedirect.com/science/article/pii/S0957417423032803" target="_blank">A review of ensemble learning and data augmentation models for class imbalanced problems: Combination, implementation and evaluation</a>
- <a href="https://unece.org/sites/default/files/2024-02/Data%20editing%20of%20ADSaMM%20group%202023.pdf" target="_blank">UNECE - Organisational aspects of implementing ML based data editing in statistical production</a>
- <a href="https://statswiki.unece.org/spaces/ML/pages/290358735/WP1+-+Theme+2+Edit+and+Imputation+Report" target="_blank">UNECE – HLG-MOS Machine Learning Project Edit and Imputation Theme Report</a>


---

### Quality

- <a href="https://doi.org/10.1007/s11943-023-00330-0" target="_blank">Van Delden, A., J. Burger, and M. Puts. 2023. ‘‘Ten Propositions on Machine Learning in Official Statistics.’’ AStA Wirtschafts- und Sozialstatistisches Archiv 17 (3): 195–221. DOI: https://doi.org/10.1007/s11943-023-00330-0</a>
- Kowarik, A., et al (2020). "Deliverable K3: Revised Version of the Quality Guidelines for the Acquisition and Usage of Big Data", Work Package K Methodology and quality, ESSnet Big Data II
- Reinert, R., et al (2016). "Work Package 1: Checklist for Evaluating the Quality of Input Data", ESSnet KOMUSO
- <a href="https://journals.sagepub.com/doi/10.3233/SJI-180468" target="_blank">De Waal, T., et al (2019). "Quality measures for multisource statistics." Statistical Journal of the IAOS 35.2</a>
- <a href="https://cros.ec.europa.eu/book-page/web-intelligence-network-reports" target="_blank">Kowarik, A., et al (2025). "Deliverable 4.5: Quality Guidelines for acquiring and using web scraped data", Work Package 4 Methodology and quality, ESSnet Trusted Smart Statistcs – Web IntelligenceNetwork</a>
- <a href="https://artificialintelligenceact.eu/high-level-summary/" target="_blank">AI Act: High Level Summary</a>
- <a href="https://unece.org/sites/default/files/2024-10/MWW2024_S5_1_Finland_Piela_P.pdf" target="_blank">Piela R., (2024). "Incorporating AI into Statistical Standards: Enhancing GSBPM with (Generative) AI" UNECE|ModernStats World Workshop, October 2024</a>
- <a href="https://digital-strategy.ec.europa.eu/en/library/guidelines-scope-obligationsproviders-general-purpose-ai-models-under-ai-act" target="_blank">GPAI models gudelines</a>
- <a href="https://doi.org/10.1007/s11943-023-00329-7" target="_blank">Saidani, Y., Dumpert, F., Borgs, C., Brand, A., Nickl, A., Rittmann, A., Rohde, J., Salwiczek, C., Storfinger, N., and Straub, S. 2023. "Qualitätsdimensionen maschinellen Lernens in der amtlichen Statistik." AStA Wirtschafts- und Sozialstatistisches Archiv 17: 253–303. DOI: https://doi.org/10.1007/s11943-023-00329-7
</a>
- <a href="https://doi.org/10.1007/978-3-032-10004-7_4" target="_blank">Y. Saidani, F. Dumpert, Quality dimensions and quality guidelines for machine learning in official statistics, in Foundations and Advances of Machine Learning in Official Statistics, F.Dumpert, Chap.4 (Springer, Berlin, 2025). DOI: https://doi.org/10.1007/978-3-032-10004-7_4
</a>
- <a href="https://unece.org/statistics/publications/machine-learning-official-statistics" target="_blank">United Nations Economic Commission for Europe (UNECE) (2021) Machine learning for official statistics</a>
- <a href="statswiki.unece.org/download/attachments/120128748/The%20use%20of%20machine%20learning%20in%20official%20statistics.pdf" target="_blank">Yung W, Karkimaa J, Scannapieco M, Barcarolli G, Zardetto D, Sanchez JAR, Braaksma B, Buelens B, Burger J. 2018. The use of machine learning in official statistics. </a>
- <a href="https://journals.sagepub.com/doi/abs/10.3233/SJI-210875" target="_blank">Yung, W., T. Siu-Ming, B. Buelens, H. Chipman, F. Dumpert, G. Ascari, F. Rocci, J. Burger, and I. Choi. 2022. "A quality framework for statistical algorithms." Statistical Journal of the IAOS 38: 291-308.</a>




---

### Other resources

- Text classification for Ecoicop classification
- machine learning introductory lecture Statistics Norway
- Handbook of Statistical Data Editing and Imputation
- The Elements of Statistical Learning: Data Mining, Inference, and Prediction.  Springer Series in Statistics
- Machine Learning Refined: Foundations, Algorithms, and Applications. Cambridge University Press

---

#### Papers and publications

- <a href="https://link.springer.com/book/10.1007/978-3-032-10004-7" target="_blank">Foundations and Advances of Machine Learning in Official Statistics</a>. Florian Dumpert, Springer (2025)
- <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/sjos.12626" target="_blank">Robust quasi-randomization-based estimation with ensemble learning for missing data</a>. Scandinavian Journal of Statistics
- <a href="https://www.sciencedirect.com/science/article/pii/S0957417423032803" target="_blank">A review of ensemble learning and data augmentation models for class imbalanced problems: Combination, implementation and evaluation</a>. Expert Systems with Applications
- <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3250568/" target="_blank">Probability machines: consistent probability estimation using nonparametric learning machines.</a>.  Methods Inf Med.
- <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC6368971/" target="_blank">Splitting on categorical predictors in random forests.</a>. PeerJ.
- <a href="https://journals.sagepub.com/doi/10.1177/0282423X241309971" target="_blank">A Score Function to Prioritize Editing in Household Survey Data: A Machine Learning Approach</a>. Journal of Official Statistics
- <a href="https://unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.44/2015/mtg1/WP_31_New_Zealand_Let_the_data_speak_ML_methods_for_data_editing_and_imputation.pdf" target="_blank">Let the data speak: Machine learning methods for data editing and imputation</a>. UNECE / Work Session on Statistical Data Editing
- <a href="https://statswiki.unece.org/spaces/ML/pages/279775961/Studies+and+Codes?preview=/285216428/290358686/ML_WP1_EI_Italy_RocciVarriale.pdf" target="_blank">Machine Learning tool for editing in the Italian Register of the Public Administration, a proposal</a>. UNECE HLG-MOS Machine Learning Project
- Data cleaning and machine learning: a systematic literature review. Autom Softw Eng
- <a href="https://unece.org/sites/default/files/2024-10/SDE2024_S2_Lithuania_Burakauskait%C4%97_D.pdf" target="_blank">Moving towards the standardized process of automatic statistical data editing using machine learning techniques</a>. UNECE Expert Meeting on Statistical Data Editing
- <a href="https://unece.org/sites/default/files/2022-10/SDE2022_S3_Italy_delMonaco_D.pdf" target="_blank">Stacking machine-learning models for anomaly detection: comparing AnaCredit to other banking datasets</a>. UNECE Expert Meeting on Statistical Data Editing
- <a href="https://unece.org/sites/default/files/2022-10/SDE2022_S4_Spain_Barrag%C3%A1n%20%26%20Salgado_D.pdf" target="_blank">Improving statistical data editing with Machine Learning: first use cases in Statistics Spain (INE)</a>. UNECE Expert Meeting on Statistical Data Editing
- <a href="https://unece.org/sites/default/files/2022-10/SDE2022_S6_Chile_Vasquez_D.pdf" target="_blank">Automatic selective editing approach using machine learning: an application to VAT data</a>. UNECE Expert Meeting on Statistical Data Editing






---



### USGS 

A selection of resources from the United States Geological Survey about use of R.


#### Beyond Basic R

- <a href="https://waterdata.usgs.gov/blog/reproducibility/" target="_blank">The case for reproducibility</a>
- <a href="https://waterdata.usgs.gov/blog/intro-best-practices/" target="_blank">Beyond Basic R - Introduction and Best Practices</a>
- <a href="https://waterdata.usgs.gov/blog/beyond-basic-git/" target="_blank">Beyond Basic R - Version Control with Git</a>
- <a href="https://waterdata.usgs.gov/blog/beyond-basic-mapping/" target="_blank">Beyond Basic R - Mapping</a>
- <a href="https://waterdata.usgs.gov/blog/beyond-basic-plotting/" target="_blank">Beyond Basic R - Plotting with ggplot2 and Multiple Plots in One Figure</a>
- <a href="https://waterdata.usgs.gov/blog/data-munging/" target="_blank">Beyond Basic R - Data Munging</a>
- <a href="https://waterdata.usgs.gov/blog/beyond-basic-mapping/" target="_blank">Beyond Basic R - Data Munging</a>


#### Reproducible Data Science in R

- <a href="https://waterdata.usgs.gov/blog/rds-assertions/" target="_blank">Reproducible Data Science in R: Say the quiet part out loud with assertion tests</a>
- <a href="https://waterdata.usgs.gov/blog/rds-function-evaluation/" target="_blank">Reproducible Data Science in R: Flexible functions using tidy evaluation</a>
- <a href="https://waterdata.usgs.gov/blog/rds-better-functions/" target="_blank">Reproducible Data Science in R: Writing better functions</a>
- <a href="https://waterdata.usgs.gov/blog/rds-functions-that-work-for-you/" target="_blank">Reproducible Data Science in R: Writing functions that work for you</a>
- <a href="https://waterdata.usgs.gov/blog/rds-iterate/" target="_blank">Reproducible Data Science in R: Iterate, don't duplicate</a>

#### Other topics

- <a href="https://waterdata.usgs.gov/blog/quarto-template-demo/" target="_blank">Duplicating Quarto elements with code templates to reduce copy and paste errors</a>
- <a href="https://waterdata.usgs.gov/blog/tidycensus-viz/" target="_blank">Charting 'tidycensus' data with R</a>



